### PR TITLE
Update Patrick Trottier Info

### PR DESCRIPTION
**Pull request by Coder206**
Here are a few additions to my profile :)

### CODE REVIEW

**Comment by dbs** [comment]
Thanks @Coder206 - your updates should now be visible on the production website!

**Comment by Coder206** [comment]
@dbs Thanks! :) Looks great! There seems to be something wrong with the Service Worker... (for the FireFox issue)

**Comment by dbs** [comment]
Yeah, "Corrupted Content Error" is what I see on Firefox when on Chrome I get the notification about a newer version of the web app being available; perhaps related to https://bugzilla.mozilla.org/show_bug.cgi?id=1280413 -- feel like trying to figure out where our code is doing something wrong? You could be a hero to upstream!

**Comment by Coder206** [comment]
@dbs I looked into this further, there is a error thrown on an event related to caching when running on Firefox within the Service Worker. However, I learned the template Hoverboard uses a Google framework for Service Workers which has already a patch for the issue, it just hasn't been released yet...

**Pull request merged**
